### ISSUE TITLE
댓글 페이징 여부, 게시글 조회(유저 포함)

### ISSUE THREAD

**Issue by java-saeng** [Runvengers/Running-Mate-Front#77]
1. 게시글 조회할 때 댓글도 페이징이 필요할까요?

2. 게시글에서 myrun, 유저에서 mypage 같은 URI가 따로 필요하나요??
생각해보니까 mypage라는 api를 매핑하는 것보다 같은 user/{nickName} URI에서 조회하는 게 restful할 것 같아서요~
나의 게시글 조회, 나의 정보 조회 둘 다 포함입니다

확인 부탁드립니다!

**Comment by oct-sky-out** [comment]
에브리타임을 예시로들자면 이전 댓글보기 라는 버튼을 눌러서 api요청하는 사례는 봤어요.

그리고 페이스북 같은 경우도 똑같이 아래로 내리면 다음 페이지 댓글 응답주고요.

물론 안그런 케이스의 플렛폼도 있겠지만 그건 짧은 문자를 주고 받을 수 있는 학교나 홈페이지 문의사항같은 케이스는 안할거같네요.

**Comment by oct-sky-out** [comment]
2번의 경우 백엔드에서 최대한 Restful하게 설계하시고, 저희에게 API솔루션을 간단히 설명해주시면 얼마든지 바꾸셔도 좋습니다.
