### ISSUE TITLE
크루 이름 변경 

### ISSUE THREAD

**Issue by java-saeng** [Runvengers/Running-Mate-Front#78]
![image](https://user-images.githubusercontent.com/62413589/149945079-c0605cf1-a672-421b-b064-5acbae0fd67a.png)

크루 이름 변경 

기존 : 바꿀 이름을 쿼리 스트링으로 전달

변경 : body에 부탁합니다  변수명 : newName

**Comment by oct-sky-out** [comment]
네 본부대로 하겠습니다!

**Comment by java-saeng** [comment]
![image](https://user-images.githubusercontent.com/62413589/149988150-47b64fec-4268-48f5-960d-1620f34bbb13.png)


재수정 있습니다.

기존 : 바꿀 이름을 body에 json으로 전달

변경 : 바꿀 이름을 body에 content-type은 text/plain으로 부탁드립니다

**Comment by oct-sky-out** [comment]
@java-saeng  위 풀리퀘스트에 커밋된 [기능구현] 크루 제거, 크루 이름변경 구현 (이후 사가 적용 예정) 커밋의 frontend/src/lib/api/crewService.ts 참조하시고 궁금하신 부분은 코멘트 주세요.
